name: Build
on:
  pull_request:
  push:
    branches:
      - 'main'
permissions: {}
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
  check:
    name: Check Codestyle
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.4"
          tools: phive
      - name: Install codesniffer
        run: |
            cd tools/phpcs
            composer install
            cd ../..
      - name: Install
        run: composer install
      - name: check
        run: ./tools/phpcs/vendor/bin/phpcs
  xml-lint:
    name: Lint XML-Files
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.4"
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - name: lint
        run: composer lintxml
  test:
    needs: [check, xml-lint]
    runs-on: ubuntu-latest # ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        # operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        icu-versions: ['74.1', '73.2', '73.1', '71.1', '69.1', '67.1']
        experimental: [false]
        include:
          - php-versions: '8.6'
            icu-versions: '74.1'
            experimental: true
    name: "PHP ${{ matrix.php-versions }}-icu${{ matrix.icu-versions }} # Test on ${{ matrix.operating-system }}"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: sodium, intl-${{matrix.icu-versions}}
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
      - name: prepare
        run: composer update
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit
      - name: test
        run: composer test
#  upload-xsd-file:
#    needs: [xml-lint, test]
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    continue-on-error: false
#    environment: github-actions
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v7
#      - name: Upload XST-File to heigl.org
#        shell: bash
#        env:
#          FTP_USER: ${{ secrets.FTP_USER }}
#          FTP_PASS: ${{ secrets.FTP_PASS }}
#        run: |
#          curl --ftp-create-dirs -T share/holidays.xsd -u "$FTP_USER":"$FTP_PASS" ftp://ftp.heigl.org:21/holidays.xsd
  analyze:
    name: Run static analysis
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.4"
      - name: Download phpstan
        run: |
            composer require phpstan/phpstan
      - name: install
        run: composer update --no-dev
      - name: analyze
        run: ./vendor/bin/phpstan
  coverage:
    name: Create code-coverage
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.4"
          coverage: xdebug
      - name: Install
        run: composer update
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit
      - name: run testsuite
        run: composer test-coverage
      - name: upload to coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v
      - name: upload to codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # 7.0.0
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./clover.xml # optional
          #flags: unittests # optional
          #name: codecov-umbrella # optional
          #fail_ci_if_error: true # optional (default = false)
          #verbose: true # optional (default = false)
