name: Build
on:
  pull_request:
  push:
    branches:
      - 'main'
permissions: {}
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
  check:
    name: Check Codestyle
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.4"
          tools: phive
      - name: Install codesniffer
        run: |
            cd tools/phpcs
            composer install
            cd ../..
      - name: Install
        run: composer install
      - name: check
        run: ./tools/phpcs/vendor/bin/phpcs
  xml-lint:
    name: Lint XML-Files
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.4"
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - name: lint
        run: composer lintxml
  test:
    needs: [check, xml-lint]
    runs-on: ubuntu-latest # ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        # All currently supported PHP-Versions are tested against all ICU-versions that were active since release of
        # the oldest PHP-Version
        php-versions: ['8.2', '8.3', '8.4', '8.5']
        icu-versions: ['74.1', '74.2', '75.1', '76.1', '77.1', '78.1', '78.2', '78.3']
        experimental: [false]
        include:
          # The nightly version is only tested against the latest ICU-version
          - php-versions: '8.6'
            icu-versions: '78.3'
            experimental: true
          - php-versions: '7.3' # EOL 06.12.2021, last release: 7.3.33 on 18.11.2021
            icu-versions: '70.1' # release: 28.10.2021
            experimental: false
          - php-versions: '7.4' # EOL 28.11.2022, last release: 7.4.33 on 03.11.2022
            icu-versions: '72.1' # release: 18.10.2022
            experimental: false
          - php-versions: '8.0' # EOL 26.11.2023, last release: 8.0.30 on 03.08.2023
            icu-versions: '73.2' # release: 13.06.2023
            experimental: false
          - php-versions: '8.1' # EOL 31.12.2025, last release: 8.1.34 on 18.12.2025
            icu-versions: '78.1' # release: 30.10.2023
            experimental: false
    name: "Test on PHP ${{ matrix.php-versions }} with icu${{ matrix.icu-versions }}"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: sodium, intl-${{matrix.icu-versions}}
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
      - name: prepare
        run: composer update
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit
      - name: test
        run: composer test
#  upload-xsd-file:
#    needs: [xml-lint, test]
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    continue-on-error: false
#    environment: github-actions
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v7
#      - name: Upload XST-File to heigl.org
#        shell: bash
#        env:
#          FTP_USER: ${{ secrets.FTP_USER }}
#          FTP_PASS: ${{ secrets.FTP_PASS }}
#        run: |
#          curl --ftp-create-dirs -T share/holidays.xsd -u "$FTP_USER":"$FTP_PASS" ftp://ftp.heigl.org:21/holidays.xsd
  analyze:
    name: Run static analysis
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.4"
      - name: Download phpstan
        run: |
            composer require phpstan/phpstan
      - name: install
        run: composer update --no-dev
      - name: analyze
        run: ./vendor/bin/phpstan
  coverage:
    name: Create code-coverage
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.4"
          coverage: xdebug
      - name: Install
        run: composer update
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit
      - name: run testsuite
        run: composer test-coverage
      - name: upload to coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v
      - name: upload to codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # 7.0.0
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./clover.xml # optional
          #flags: unittests # optional
          #name: codecov-umbrella # optional
          #fail_ci_if_error: true # optional (default = false)
          #verbose: true # optional (default = false)
